// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Author) IsEntity() {}

type NewAuthor struct {
	Name string `json:"name"`
}
