package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/smallretardedfish/gql-federation/medication/graph/model"
)

// FindMedicationByID is the resolver for the findMedicationByID field.
func (r *entityResolver) FindMedicationByID(ctx context.Context, id int64) (*model.Medication, error) {
	return r.MedicationStore.GetMedication(ctx, id)
}

// FindOrganizationByID is the resolver for the findOrganizationByID field.
func (r *entityResolver) FindOrganizationByID(ctx context.Context, id int64) (*model.Organization, error) {
	return &model.Organization{
		ID: id,
	}, nil
}

// FindPatientByID is the resolver for the findPatientByID field.
func (r *entityResolver) FindPatientByID(ctx context.Context, id int64) (*model.Patient, error) {
	return &model.Patient{
		ID: id,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
