package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/smallretardedfish/gql-federation/condition/graph/model"
)

// FindConditionByID is the resolver for the findConditionByID field.
func (r *entityResolver) FindConditionByID(ctx context.Context, id int64) (*model.Condition, error) {
	return r.ConditionStore.GetCondition(ctx, id)
}

// FindPatientByID is the resolver for the findPatientByID field.
func (r *entityResolver) FindPatientByID(ctx context.Context, id int64) (*model.Patient, error) {
	return &model.Patient{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
