package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/smallretardedfish/gql-federation/condition/graph/model"
)

// Conditions is the resolver for the conditions field.
func (r *queryResolver) Conditions(ctx context.Context, first int) ([]*model.Condition, error) {
	limit := int64(first)
	return r.ConditionStore.GetConditions(ctx, &ConditionFilter{Limit: &limit})
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
