package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"github.com/smallretardedfish/gql-federation/patient/dataloaders"
	"github.com/smallretardedfish/gql-federation/patient/graph/model"
)

// FindPatientByID is the resolver for the findPatientByID field.
func (r *entityResolver) FindPatientByID(ctx context.Context, id int64) (*model.Patient, error) {
	patient, err := dataloaders.GetPatient(ctx, id) // using dataloader for performance boost here
	//patient, err := r.PatientStore.GetPatient(ctx, id)
	if err != nil {
		return nil, err
	}

	return patient, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
