package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/smallretardedfish/gql-federation/patient/graph/model"
)

// Patient is the resolver for the patient field.
func (r *queryResolver) Patient(ctx context.Context, id int64) (*model.Patient, error) {
	patient, err := r.PatientStore.GetPatient(ctx, id)
	if err != nil {
		return nil, err
	}
	return patient, nil
}

// Patients is the resolver for the patients field.
func (r *queryResolver) Patients(ctx context.Context) ([]*model.Patient, error) {
	patients, err := r.PatientStore.GetPatients(ctx, nil)
	if err != nil {
		return nil, err
	}
	return patients, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
