package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"github.com/smallretardedfish/gql-federation/author-service/graph/model"
	"golang.org/x/exp/slog"
)

// FindAuthorByID is the resolver for the findAuthorByID field.
func (r *entityResolver) FindAuthorByID(ctx context.Context, id string) (*model.Author, error) {
	slog.Info("FindAuthorByID call")
	return r.AuthorStorage.Get(id)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
