// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coding struct {
	System  *string `json:"system,omitempty"`
	Code    *string `json:"code,omitempty"`
	Display *string `json:"display,omitempty"`
}

type Condition struct {
	ID       int64    `json:"id"`
	Code     *Coding  `json:"code"`
	Category *Coding  `json:"category"`
	Severity *Coding  `json:"severity"`
	Patient  *Patient `json:"patient"`
}

func (Condition) IsEntity() {}

type Patient struct {
	ID int64 `json:"id"`
}

func (Patient) IsEntity() {}
