// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coding struct {
	System  *string `json:"system,omitempty"`
	Code    *string `json:"code,omitempty"`
	Display *string `json:"display,omitempty"`
}

type Medication struct {
	ID           int64         `json:"id"`
	Code         *Coding       `json:"code"`
	Form         *Coding       `json:"form"`
	Manufacturer *Organization `json:"manufacturer,omitempty"`
	Patient      *Patient      `json:"patient,omitempty"`
}

func (Medication) IsEntity() {}

type MedicationsFilter struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Organization struct {
	ID int64 `json:"id"`
}

func (Organization) IsEntity() {}

type Patient struct {
	ID int64 `json:"id"`
}

func (Patient) IsEntity() {}
