// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coding struct {
	System  *string `json:"system,omitempty"`
	Code    *string `json:"code,omitempty"`
	Display *string `json:"display,omitempty"`
}

type Encounter struct {
	ID      int64    `json:"id"`
	Status  string   `json:"status"`
	Type    *Coding  `json:"type"`
	Period  *Period  `json:"period"`
	Patient *Patient `json:"patient"`
}

func (Encounter) IsEntity() {}

type Patient struct {
	ID         int64        `json:"id"`
	Encounters []*Encounter `json:"encounters"`
}

func (Patient) IsEntity() {}

type Period struct {
	Start *string `json:"start,omitempty"`
	End   *string `json:"end,omitempty"`
}
