package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"github.com/smallretardedfish/gql-federation/book-service/graph/model"
)

// FindAuthorByID is the resolver for the findAuthorByID field.
func (r *entityResolver) FindAuthorByID(ctx context.Context, id string) (*model.Author, error) {
	return &model.Author{
		ID:    id,
		Books: nil,
	}, nil
}

// FindBookByID is the resolver for the findBookByID field.
func (r *entityResolver) FindBookByID(ctx context.Context, id string) (*model.Book, error) {
	return r.BookStorage.Get(id)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
