package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/smallretardedfish/gql-federation/encounter/graph/model"
)

// FindEncounterByID is the resolver for the findEncounterByID field.
func (r *entityResolver) FindEncounterByID(ctx context.Context, id int64) (*model.Encounter, error) {
	enc, err := r.EncounterStore.GetEncounter(ctx, id)
	if err != nil {
		return nil, err
	}

	return enc, nil
}

// FindPatientByID is the resolver for the findPatientByID field.
func (r *entityResolver) FindPatientByID(ctx context.Context, id int64) (*model.Patient, error) {
	return &model.Patient{
		ID: id,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
