package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/smallretardedfish/gql-federation/medication/transport/graph/model"
)

// Medications is the resolver for the medications field.
func (r *queryResolver) Medications(ctx context.Context, input *model.MedicationsFilter) ([]*model.Medication, error) {
	filter := &MedicationFilter{}
	var limit, offset int64
	if input != nil {
		if input.Limit != nil {
			limit = int64(*input.Limit)
			filter.Limit = &limit
		}

		if input.Offset != nil {
			offset = int64(*input.Offset)
			filter.Offset = &offset
		}
	}

	medications, err := r.MedicationStore.GetMedications(ctx, filter)
	if err != nil {
		return nil, err
	}

	return medications, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
